"""empty message

Revision ID: 0937d4b0c799
Revises: 9de4f41d897f
Create Date: 2022-04-23 23:29:58.687970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0937d4b0c799'
down_revision = '9de4f41d897f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'moves',
               existing_type=sa.VARCHAR(length=12000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'moves',
               existing_type=sa.VARCHAR(length=12000),
               nullable=False)
    # ### end Alembic commands ###
