"""empty message

Revision ID: 11215845eb03
Revises: 56ba3ee38309
Create Date: 2022-04-23 13:51:14.897114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11215845eb03'
down_revision = '56ba3ee38309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('board_one', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('board_two', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('games', 'board')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('board', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('games', 'board_two')
    op.drop_column('games', 'board_one')
    # ### end Alembic commands ###
