"""empty message

Revision ID: 56ba3ee38309
Revises: aa2791a9a6e9
Create Date: 2022-04-23 13:41:57.752747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56ba3ee38309'
down_revision = 'aa2791a9a6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('board', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('turn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'turn')
    op.drop_column('games', 'board')
    # ### end Alembic commands ###
