"""empty message

Revision ID: 9de4f41d897f
Revises: 11215845eb03
Create Date: 2022-04-23 15:17:42.792452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9de4f41d897f'
down_revision = '11215845eb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('board', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('games', 'board_one')
    op.drop_column('games', 'board_two')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('board_two', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('board_one', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('games', 'board')
    # ### end Alembic commands ###
